from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class IAuthService(Protocol):
    def hash_password(self, password: str) -> str: ...
    def verify_password(self, plain: str, hashed: str) -> bool: ...
    def create_access_token(self, data: dict) -> str: ...
    def create_refresh_token(self, data: dict) -> str: ...
    def decode_token(self, token: str) -> Optional[dict]: ...
